### ISSUE TITLE
Error: No time format was found in parser for: Current Favorites

### ISSUE THREAD

**Issue by BeepSterr** [axi92/steam-workshop-scraper#70]
```
const workshop_id = '2630451788';
const workshop_data = await sws.GetInfo(workshop_id);
```
```
Error: No time format was found in parser for: Current Favorites30 Oct, 2021 @ 7:09am
    at SteamWorkshopScraper.ParseSteamTime (/Users/admin/PhpstormProjects/discord.steamlinker/node_modules/steam-workshop-scraper/index.js:176:13)
    at Object.convert (/Users/admin/PhpstormProjects/discord.steamlinker/node_modules/steam-workshop-scraper/index.js:18:28)
    at /Users/admin/PhpstormProjects/discord.steamlinker/node_modules/scrape-it-core/lib/index.js:199:34
    at iterateObject (/Users/admin/PhpstormProjects/discord.steamlinker/node_modules/iterate-object/lib/index.js:28:17)
    at handleDataObj (/Users/admin/PhpstormProjects/discord.steamlinker/node_modules/scrape-it-core/lib/index.js:119:9)
    at module.exports [as scrapeHTML] (/Users/admin/PhpstormProjects/discord.steamlinker/node_modules/scrape-it-core/lib/index.js:208:12)
    at scrapeIt (/Users/admin/PhpstormProjects/discord.steamlinker/node_modules/scrape-it/lib/index.js:26:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseCommunity (file:///Users/admin/PhpstormProjects/discord.steamlinker/src/lib/parser.js:37:35)
    at async urlToEmbed (file:///Users/admin/PhpstormProjects/discord.steamlinker/src/lib/parser.js:18:20)
```

**Comment by axi92** [comment]
In the next version you can do that and will get an object back like this:
```
{
  title: 'ark mods',
  timePublished: '2018-12-30T18:12:00.000+01:00',
  timeUpdated: '2020-12-23T05:38:00.000+01:00',
  image: 'https://steamuserimages-a.akamaihd.net/ugc/961981476968230982/F42049DE8EF590E07C203AADFEA7D5CED14DB645/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false',
  data: [
    1260983937, 1136125765,
    1814953878,  751991809,
    1609138312, 1890886098,
    1846137966, 1846109576,
     905971515, 1999447172,
     761535755, 1757776400,
    1435344008, 2147192126,
     821530042, 2078950332,
    2211111509, 2053416662
  ]
}
```
